/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "Readers/Calculator/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System.Text;
using System.Collections.Generic;
using System.Linq;
using System;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace Calculator
{
public partial class ParserFactory
{

public static void createEdges0(int[,] __edges_table__)
{
__edges_table__[0,2] = 2;
__edges_table__[0,4] = 3;
__edges_table__[0,5] = 4;
__edges_table__[0,6] = 5;
__edges_table__[0,7] = 6;
__edges_table__[0,8] = 7;
__edges_table__[0,14] = 8;
__edges_table__[0,16] = 1;
__edges_table__[1,9] = 9;
__edges_table__[1,10] = 10;
__edges_table__[1,11] = 11;
__edges_table__[1,12] = 12;
__edges_table__[1,13] = 13;
__edges_table__[2,2] = 2;
__edges_table__[2,4] = 3;
__edges_table__[2,5] = 4;
__edges_table__[2,6] = 5;
__edges_table__[2,7] = 6;
__edges_table__[2,8] = 7;
__edges_table__[2,14] = 8;
__edges_table__[2,16] = 14;
__edges_table__[3,2] = 15;
__edges_table__[4,2] = 16;
__edges_table__[5,2] = 17;
__edges_table__[9,2] = 2;
__edges_table__[9,4] = 3;
__edges_table__[9,5] = 4;
__edges_table__[9,6] = 5;
__edges_table__[9,7] = 6;
__edges_table__[9,8] = 7;
__edges_table__[9,14] = 8;
__edges_table__[9,16] = 18;
__edges_table__[10,2] = 2;
__edges_table__[10,4] = 3;
__edges_table__[10,5] = 4;
__edges_table__[10,6] = 5;
__edges_table__[10,7] = 6;
__edges_table__[10,8] = 7;
__edges_table__[10,14] = 8;
__edges_table__[10,16] = 19;
__edges_table__[11,2] = 2;
__edges_table__[11,4] = 3;
__edges_table__[11,5] = 4;
__edges_table__[11,6] = 5;
__edges_table__[11,7] = 6;
__edges_table__[11,8] = 7;
__edges_table__[11,14] = 8;
__edges_table__[11,16] = 20;
__edges_table__[12,2] = 2;
__edges_table__[12,4] = 3;
__edges_table__[12,5] = 4;
__edges_table__[12,6] = 5;
__edges_table__[12,7] = 6;
__edges_table__[12,8] = 7;
__edges_table__[12,14] = 8;
__edges_table__[12,16] = 21;
__edges_table__[13,2] = 2;
__edges_table__[13,4] = 3;
__edges_table__[13,5] = 4;
__edges_table__[13,6] = 5;
__edges_table__[13,7] = 6;
__edges_table__[13,8] = 7;
__edges_table__[13,14] = 8;
__edges_table__[13,16] = 22;
__edges_table__[14,3] = 23;
__edges_table__[14,9] = 9;
__edges_table__[14,10] = 10;
__edges_table__[14,11] = 11;
__edges_table__[14,12] = 12;
__edges_table__[14,13] = 13;
__edges_table__[15,2] = 2;
__edges_table__[15,4] = 3;
__edges_table__[15,5] = 4;
__edges_table__[15,6] = 5;
__edges_table__[15,7] = 6;
__edges_table__[15,8] = 7;
__edges_table__[15,14] = 8;
__edges_table__[15,16] = 24;
__edges_table__[16,2] = 2;
__edges_table__[16,4] = 3;
__edges_table__[16,5] = 4;
__edges_table__[16,6] = 5;
__edges_table__[16,7] = 6;
__edges_table__[16,8] = 7;
__edges_table__[16,14] = 8;
__edges_table__[16,16] = 25;
__edges_table__[17,2] = 2;
__edges_table__[17,4] = 3;
__edges_table__[17,5] = 4;
__edges_table__[17,6] = 5;
__edges_table__[17,7] = 6;
__edges_table__[17,8] = 7;
__edges_table__[17,14] = 8;
__edges_table__[17,16] = 26;
__edges_table__[18,9] = 9;
__edges_table__[18,10] = 10;
__edges_table__[18,11] = 11;
__edges_table__[18,12] = 12;
__edges_table__[18,13] = 13;
__edges_table__[19,9] = 9;
__edges_table__[19,10] = 10;
__edges_table__[19,11] = 11;
__edges_table__[19,12] = 12;
__edges_table__[19,13] = 13;
__edges_table__[20,9] = 9;
__edges_table__[20,10] = 10;
__edges_table__[20,11] = 11;
__edges_table__[20,12] = 12;
__edges_table__[20,13] = 13;
__edges_table__[21,9] = 9;
__edges_table__[21,10] = 10;
__edges_table__[21,11] = 11;
__edges_table__[21,12] = 12;
__edges_table__[21,13] = 13;
__edges_table__[22,9] = 9;
__edges_table__[22,10] = 10;
__edges_table__[22,11] = 11;
__edges_table__[22,12] = 12;
__edges_table__[22,13] = 13;
__edges_table__[24,3] = 27;
__edges_table__[24,9] = 9;
__edges_table__[24,10] = 10;
__edges_table__[24,11] = 11;
__edges_table__[24,12] = 12;
__edges_table__[24,13] = 13;
__edges_table__[25,3] = 28;
__edges_table__[25,9] = 9;
__edges_table__[25,10] = 10;
__edges_table__[25,11] = 11;
__edges_table__[25,12] = 12;
__edges_table__[25,13] = 13;
__edges_table__[26,3] = 29;
__edges_table__[26,9] = 9;
__edges_table__[26,10] = 10;
__edges_table__[26,11] = 11;
__edges_table__[26,12] = 12;
__edges_table__[26,13] = 13;
}
public static IEnumerable<NfaCell<TokenEnum, object>>[,] createRecoveryTable()
{
var __recovery_table__ = new IEnumerable<NfaCell<TokenEnum,object>>[30,17];
return __recovery_table__;
}
public static StringRep<TokenEnum> createSymbolsRep()
{
var symbols_rep = StringRep.Create(Tuple.Create(TokenEnum.Error,"Error"),
Tuple.Create(TokenEnum.EOF,"EOF"),
Tuple.Create(TokenEnum.__term0,"__term0"),
Tuple.Create(TokenEnum.__term1,"__term1"),
Tuple.Create(TokenEnum.sin,"sin"),
Tuple.Create(TokenEnum.cos,"cos"),
Tuple.Create(TokenEnum.sqrt,"sqrt"),
Tuple.Create(TokenEnum.pi,"pi"),
Tuple.Create(TokenEnum.e,"e"),
Tuple.Create(TokenEnum.PLUS,"PLUS"),
Tuple.Create(TokenEnum.MINUS,"MINUS"),
Tuple.Create(TokenEnum.MULT,"MULT"),
Tuple.Create(TokenEnum.DIV,"DIV"),
Tuple.Create(TokenEnum.POWER,"POWER"),
Tuple.Create(TokenEnum.NUM,"NUM"),
Tuple.Create(TokenEnum.s,"s"),
Tuple.Create(TokenEnum.exp,"exp"));
return symbols_rep;
}
public Parser<TokenEnum,object> CreateParser()
{
Parser<TokenEnum,object> parser = null;
 // Identity functions (x => x) are used directly without storing them in `functions` variables
var __functions_0__ = new Func<object,object>((x) => x); // s
var __functions_1__ = new Func<object,IMathNode,object,object>((_0,exp,_2) => exp); // exp
var __functions_2__ = new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => new AddNode(e1, e2)); // exp
var __functions_3__ = new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => new SubNode(e1, e2)); // exp
var __functions_4__ = new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => new MultNode(e1, e2)); // exp
var __functions_5__ = new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => new DivNode(e1, e2)); // exp
var __functions_6__ = new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => new PowNode(e1, e2)); // exp
var __functions_7__ = new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => new SinNode(exp)); // exp
var __functions_8__ = new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => new CosNode(exp)); // exp
var __functions_9__ = new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => new SqrtNode(exp)); // exp
var __functions_10__ = new Func<object,object>((_0) => new NumNode(Math.PI)); // exp
var __functions_11__ = new Func<object,object>((_0) => new NumNode(Math.E)); // exp
var __functions_12__ = new Func<double,object>((NUM) => new NumNode(NUM)); // exp
var __actions_table__ = new IEnumerable<ParseAction<TokenEnum,object>>[30,17];__actions_table__[0,2] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(true)};__actions_table__[1,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.s,
1,
null,
-1,
"Action for \"s\" at (48,6)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object>((exp) => __functions_0__(exp)),0))
))};__actions_table__[6,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
1,
null,
-1,
"Action for \"exp\" at (68,11)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_10__(_0)),1))
))};__actions_table__[7,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
1,
null,
-1,
"Action for \"exp\" at (70,10)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_11__(_0)),1))
))};__actions_table__[8,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
1,
null,
-1,
"Action for \"exp\" at (72,8)",
null,
ProductionAction<object>.Convert(new Func<double,object>((NUM) => __functions_12__(NUM)),0))
))};__actions_table__[18,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (52,12)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => __functions_2__(e1,_1,e2)),0))
))};__actions_table__[19,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (54,8)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => __functions_3__(e1,_1,e2)),0))
))};__actions_table__[20,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (56,8)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => __functions_4__(e1,_1,e2)),0))
))};__actions_table__[21,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (58,8)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => __functions_5__(e1,_1,e2)),0))
))};__actions_table__[22,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (60,8)",
null,
ProductionAction<object>.Convert(new Func<IMathNode,object,IMathNode,object>((e1,_1,e2) => __functions_6__(e1,_1,e2)),0))
))};__actions_table__[23,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
3,
null,
-1,
"Action for \"exp\" at (50,11)",
null,
ProductionAction<object>.Convert(new Func<object,IMathNode,object,object>((_0,exp,_2) => __functions_1__(_0,exp,_2)),1))
))};__actions_table__[27,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
4,
null,
-1,
"Action for \"exp\" at (62,12)",
null,
ProductionAction<object>.Convert(new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => __functions_7__(_0,_1,exp,_3)),2))
))};__actions_table__[28,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
4,
null,
-1,
"Action for \"exp\" at (64,12)",
null,
ProductionAction<object>.Convert(new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => __functions_8__(_0,_1,exp,_3)),2))
))};__actions_table__[29,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.exp,
4,
null,
-1,
"Action for \"exp\" at (66,13)",
null,
ProductionAction<object>.Convert(new Func<object,object,IMathNode,object,object>((_0,_1,exp,_3) => __functions_9__(_0,_1,exp,_3)),2))
))};
actionsTableDuplicates0(__actions_table__);
var __edges_table__ = ActionTableData<TokenEnum,object>.CreateEdgesTable(30,17);
createEdges0(__edges_table__);
var __recovery_table__ = createRecoveryTable();
var symbols_rep = createSymbolsRep();
parser = new Parser<TokenEnum,object>(new ActionTableData<TokenEnum,object>(
actionsTable:__actions_table__,edgesTable:__edges_table__,recoveryTable:__recovery_table__,startSymbol:TokenEnum.s,eofSymbol:TokenEnum.EOF,syntaxErrorSymbol:TokenEnum.Error,lookaheadWidth:1),symbols_rep);
return parser;
}

public static void actionsTableDuplicates0(IEnumerable<ParseAction<TokenEnum,object>>[,] __actions_table__)
{
__actions_table__[0,4] = __actions_table__[0,2];
__actions_table__[0,5] = __actions_table__[0,2];
__actions_table__[0,6] = __actions_table__[0,2];
__actions_table__[0,7] = __actions_table__[0,2];
__actions_table__[0,8] = __actions_table__[0,2];
__actions_table__[0,14] = __actions_table__[0,2];
__actions_table__[1,9] = __actions_table__[0,2];
__actions_table__[1,10] = __actions_table__[0,2];
__actions_table__[1,11] = __actions_table__[0,2];
__actions_table__[1,12] = __actions_table__[0,2];
__actions_table__[1,13] = __actions_table__[0,2];
__actions_table__[2,2] = __actions_table__[0,2];
__actions_table__[2,4] = __actions_table__[0,2];
__actions_table__[2,5] = __actions_table__[0,2];
__actions_table__[2,6] = __actions_table__[0,2];
__actions_table__[2,7] = __actions_table__[0,2];
__actions_table__[2,8] = __actions_table__[0,2];
__actions_table__[2,14] = __actions_table__[0,2];
__actions_table__[3,2] = __actions_table__[0,2];
__actions_table__[4,2] = __actions_table__[0,2];
__actions_table__[5,2] = __actions_table__[0,2];
__actions_table__[6,3] = __actions_table__[6,1];
__actions_table__[6,9] = __actions_table__[6,1];
__actions_table__[6,10] = __actions_table__[6,1];
__actions_table__[6,11] = __actions_table__[6,1];
__actions_table__[6,12] = __actions_table__[6,1];
__actions_table__[6,13] = __actions_table__[6,1];
__actions_table__[7,3] = __actions_table__[7,1];
__actions_table__[7,9] = __actions_table__[7,1];
__actions_table__[7,10] = __actions_table__[7,1];
__actions_table__[7,11] = __actions_table__[7,1];
__actions_table__[7,12] = __actions_table__[7,1];
__actions_table__[7,13] = __actions_table__[7,1];
__actions_table__[8,3] = __actions_table__[8,1];
__actions_table__[8,9] = __actions_table__[8,1];
__actions_table__[8,10] = __actions_table__[8,1];
__actions_table__[8,11] = __actions_table__[8,1];
__actions_table__[8,12] = __actions_table__[8,1];
__actions_table__[8,13] = __actions_table__[8,1];
__actions_table__[9,2] = __actions_table__[0,2];
__actions_table__[9,4] = __actions_table__[0,2];
__actions_table__[9,5] = __actions_table__[0,2];
__actions_table__[9,6] = __actions_table__[0,2];
__actions_table__[9,7] = __actions_table__[0,2];
__actions_table__[9,8] = __actions_table__[0,2];
__actions_table__[9,14] = __actions_table__[0,2];
__actions_table__[10,2] = __actions_table__[0,2];
__actions_table__[10,4] = __actions_table__[0,2];
__actions_table__[10,5] = __actions_table__[0,2];
__actions_table__[10,6] = __actions_table__[0,2];
__actions_table__[10,7] = __actions_table__[0,2];
__actions_table__[10,8] = __actions_table__[0,2];
__actions_table__[10,14] = __actions_table__[0,2];
__actions_table__[11,2] = __actions_table__[0,2];
__actions_table__[11,4] = __actions_table__[0,2];
__actions_table__[11,5] = __actions_table__[0,2];
__actions_table__[11,6] = __actions_table__[0,2];
__actions_table__[11,7] = __actions_table__[0,2];
__actions_table__[11,8] = __actions_table__[0,2];
__actions_table__[11,14] = __actions_table__[0,2];
__actions_table__[12,2] = __actions_table__[0,2];
__actions_table__[12,4] = __actions_table__[0,2];
__actions_table__[12,5] = __actions_table__[0,2];
__actions_table__[12,6] = __actions_table__[0,2];
__actions_table__[12,7] = __actions_table__[0,2];
__actions_table__[12,8] = __actions_table__[0,2];
__actions_table__[12,14] = __actions_table__[0,2];
__actions_table__[13,2] = __actions_table__[0,2];
__actions_table__[13,4] = __actions_table__[0,2];
__actions_table__[13,5] = __actions_table__[0,2];
__actions_table__[13,6] = __actions_table__[0,2];
__actions_table__[13,7] = __actions_table__[0,2];
__actions_table__[13,8] = __actions_table__[0,2];
__actions_table__[13,14] = __actions_table__[0,2];
__actions_table__[14,3] = __actions_table__[0,2];
__actions_table__[14,9] = __actions_table__[0,2];
__actions_table__[14,10] = __actions_table__[0,2];
__actions_table__[14,11] = __actions_table__[0,2];
__actions_table__[14,12] = __actions_table__[0,2];
__actions_table__[14,13] = __actions_table__[0,2];
__actions_table__[15,2] = __actions_table__[0,2];
__actions_table__[15,4] = __actions_table__[0,2];
__actions_table__[15,5] = __actions_table__[0,2];
__actions_table__[15,6] = __actions_table__[0,2];
__actions_table__[15,7] = __actions_table__[0,2];
__actions_table__[15,8] = __actions_table__[0,2];
__actions_table__[15,14] = __actions_table__[0,2];
__actions_table__[16,2] = __actions_table__[0,2];
__actions_table__[16,4] = __actions_table__[0,2];
__actions_table__[16,5] = __actions_table__[0,2];
__actions_table__[16,6] = __actions_table__[0,2];
__actions_table__[16,7] = __actions_table__[0,2];
__actions_table__[16,8] = __actions_table__[0,2];
__actions_table__[16,14] = __actions_table__[0,2];
__actions_table__[17,2] = __actions_table__[0,2];
__actions_table__[17,4] = __actions_table__[0,2];
__actions_table__[17,5] = __actions_table__[0,2];
__actions_table__[17,6] = __actions_table__[0,2];
__actions_table__[17,7] = __actions_table__[0,2];
__actions_table__[17,8] = __actions_table__[0,2];
__actions_table__[17,14] = __actions_table__[0,2];
__actions_table__[18,3] = __actions_table__[18,1];
__actions_table__[18,9] = __actions_table__[18,1];
__actions_table__[18,10] = __actions_table__[18,1];
__actions_table__[18,11] = __actions_table__[0,2];
__actions_table__[18,12] = __actions_table__[0,2];
__actions_table__[18,13] = __actions_table__[0,2];
__actions_table__[19,3] = __actions_table__[19,1];
__actions_table__[19,9] = __actions_table__[19,1];
__actions_table__[19,10] = __actions_table__[19,1];
__actions_table__[19,11] = __actions_table__[0,2];
__actions_table__[19,12] = __actions_table__[0,2];
__actions_table__[19,13] = __actions_table__[0,2];
__actions_table__[20,3] = __actions_table__[20,1];
__actions_table__[20,9] = __actions_table__[20,1];
__actions_table__[20,10] = __actions_table__[20,1];
__actions_table__[20,11] = __actions_table__[20,1];
__actions_table__[20,12] = __actions_table__[20,1];
__actions_table__[20,13] = __actions_table__[0,2];
__actions_table__[21,3] = __actions_table__[21,1];
__actions_table__[21,9] = __actions_table__[21,1];
__actions_table__[21,10] = __actions_table__[21,1];
__actions_table__[21,11] = __actions_table__[21,1];
__actions_table__[21,12] = __actions_table__[21,1];
__actions_table__[21,13] = __actions_table__[0,2];
__actions_table__[22,3] = __actions_table__[22,1];
__actions_table__[22,9] = __actions_table__[22,1];
__actions_table__[22,10] = __actions_table__[22,1];
__actions_table__[22,11] = __actions_table__[22,1];
__actions_table__[22,12] = __actions_table__[22,1];
__actions_table__[22,13] = __actions_table__[0,2];
__actions_table__[23,3] = __actions_table__[23,1];
__actions_table__[23,9] = __actions_table__[23,1];
__actions_table__[23,10] = __actions_table__[23,1];
__actions_table__[23,11] = __actions_table__[23,1];
__actions_table__[23,12] = __actions_table__[23,1];
__actions_table__[23,13] = __actions_table__[23,1];
__actions_table__[24,3] = __actions_table__[0,2];
__actions_table__[24,9] = __actions_table__[0,2];
__actions_table__[24,10] = __actions_table__[0,2];
__actions_table__[24,11] = __actions_table__[0,2];
__actions_table__[24,12] = __actions_table__[0,2];
__actions_table__[24,13] = __actions_table__[0,2];
__actions_table__[25,3] = __actions_table__[0,2];
__actions_table__[25,9] = __actions_table__[0,2];
__actions_table__[25,10] = __actions_table__[0,2];
__actions_table__[25,11] = __actions_table__[0,2];
__actions_table__[25,12] = __actions_table__[0,2];
__actions_table__[25,13] = __actions_table__[0,2];
__actions_table__[26,3] = __actions_table__[0,2];
__actions_table__[26,9] = __actions_table__[0,2];
__actions_table__[26,10] = __actions_table__[0,2];
__actions_table__[26,11] = __actions_table__[0,2];
__actions_table__[26,12] = __actions_table__[0,2];
__actions_table__[26,13] = __actions_table__[0,2];
__actions_table__[27,3] = __actions_table__[27,1];
__actions_table__[27,9] = __actions_table__[27,1];
__actions_table__[27,10] = __actions_table__[27,1];
__actions_table__[27,11] = __actions_table__[27,1];
__actions_table__[27,12] = __actions_table__[27,1];
__actions_table__[27,13] = __actions_table__[27,1];
__actions_table__[28,3] = __actions_table__[28,1];
__actions_table__[28,9] = __actions_table__[28,1];
__actions_table__[28,10] = __actions_table__[28,1];
__actions_table__[28,11] = __actions_table__[28,1];
__actions_table__[28,12] = __actions_table__[28,1];
__actions_table__[28,13] = __actions_table__[28,1];
__actions_table__[29,3] = __actions_table__[29,1];
__actions_table__[29,9] = __actions_table__[29,1];
__actions_table__[29,10] = __actions_table__[29,1];
__actions_table__[29,11] = __actions_table__[29,1];
__actions_table__[29,12] = __actions_table__[29,1];
__actions_table__[29,13] = __actions_table__[29,1];
}
}
}
