/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "Readers/Calculator/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System.Text;
using System.Collections.Generic;
using System.Linq;
using System;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace Calculator
{
public enum TokenEnum
{
Error,
EOF,
__term0,
__term1,
sin,
cos,
sqrt,
pi,
e,
PLUS,
MINUS,
MULT,
DIV,
POWER,
NUM,
s,
exp
}
}
