/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "NaiveLanguageTools.MultiRegex/RegexParser/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace NaiveLanguageTools.MultiRegex.RegexParser
{
public partial class ParserFactory
{

public static void createEdges0(int[,] __edges_table__)
{
__edges_table__[0,2] = 8;
__edges_table__[0,11] = 11;
__edges_table__[0,13] = 12;
__edges_table__[0,15] = 10;
__edges_table__[0,16] = 9;
__edges_table__[0,21] = 7;
__edges_table__[0,23] = 6;
__edges_table__[0,24] = 5;
__edges_table__[0,25] = 3;
__edges_table__[0,26] = 1;
__edges_table__[0,28] = 4;
__edges_table__[0,29] = 2;
__edges_table__[2,12] = 13;
__edges_table__[4,2] = 8;
__edges_table__[4,11] = 11;
__edges_table__[4,13] = 12;
__edges_table__[4,15] = 10;
__edges_table__[4,16] = 9;
__edges_table__[4,21] = 7;
__edges_table__[4,23] = 6;
__edges_table__[4,24] = 14;
__edges_table__[6,4] = 19;
__edges_table__[6,8] = 17;
__edges_table__[6,9] = 18;
__edges_table__[6,10] = 16;
__edges_table__[6,22] = 15;
__edges_table__[8,15] = 24;
__edges_table__[8,16] = 23;
__edges_table__[8,18] = 20;
__edges_table__[8,20] = 22;
__edges_table__[8,27] = 21;
__edges_table__[12,2] = 8;
__edges_table__[12,11] = 11;
__edges_table__[12,13] = 12;
__edges_table__[12,15] = 10;
__edges_table__[12,16] = 9;
__edges_table__[12,21] = 7;
__edges_table__[12,23] = 6;
__edges_table__[12,24] = 5;
__edges_table__[12,25] = 3;
__edges_table__[12,26] = 25;
__edges_table__[12,28] = 4;
__edges_table__[12,29] = 2;
__edges_table__[13,2] = 8;
__edges_table__[13,11] = 11;
__edges_table__[13,13] = 12;
__edges_table__[13,15] = 10;
__edges_table__[13,16] = 9;
__edges_table__[13,21] = 7;
__edges_table__[13,23] = 6;
__edges_table__[13,24] = 5;
__edges_table__[13,25] = 26;
__edges_table__[13,28] = 4;
__edges_table__[19,6] = 28;
__edges_table__[19,7] = 27;
__edges_table__[20,15] = 24;
__edges_table__[20,16] = 23;
__edges_table__[20,20] = 22;
__edges_table__[20,27] = 29;
__edges_table__[21,3] = 30;
__edges_table__[21,15] = 24;
__edges_table__[21,16] = 23;
__edges_table__[21,20] = 31;
__edges_table__[23,17] = 32;
__edges_table__[25,14] = 33;
__edges_table__[27,5] = 34;
__edges_table__[27,6] = 35;
__edges_table__[28,7] = 36;
__edges_table__[29,3] = 37;
__edges_table__[29,15] = 24;
__edges_table__[29,16] = 23;
__edges_table__[29,20] = 31;
__edges_table__[32,16] = 38;
__edges_table__[35,5] = 40;
__edges_table__[35,7] = 39;
__edges_table__[36,5] = 41;
__edges_table__[39,5] = 42;
}
public static IEnumerable<NfaCell<SymbolEnum, object>>[,] createRecoveryTable()
{
var __recovery_table__ = new IEnumerable<NfaCell<SymbolEnum,object>>[43,30];
return __recovery_table__;
}
public static StringRep<SymbolEnum> createSymbolsRep()
{
var symbols_rep = StringRep.Create(Tuple.Create(SymbolEnum.Error,"Error"),
Tuple.Create(SymbolEnum.EOF,"EOF"),
Tuple.Create(SymbolEnum.LBRACKET,"LBRACKET"),
Tuple.Create(SymbolEnum.RBRACKET,"RBRACKET"),
Tuple.Create(SymbolEnum.LBRACE,"LBRACE"),
Tuple.Create(SymbolEnum.RBRACE,"RBRACE"),
Tuple.Create(SymbolEnum.COMMA,"COMMA"),
Tuple.Create(SymbolEnum.NUM,"NUM"),
Tuple.Create(SymbolEnum.PLUS,"PLUS"),
Tuple.Create(SymbolEnum.ASTERISK,"ASTERISK"),
Tuple.Create(SymbolEnum.QMARK,"QMARK"),
Tuple.Create(SymbolEnum.DOT,"DOT"),
Tuple.Create(SymbolEnum.OR,"OR"),
Tuple.Create(SymbolEnum.LPAREN,"LPAREN"),
Tuple.Create(SymbolEnum.RPAREN,"RPAREN"),
Tuple.Create(SymbolEnum.CLASS,"CLASS"),
Tuple.Create(SymbolEnum.CHAR,"CHAR"),
Tuple.Create(SymbolEnum.MINUS,"MINUS"),
Tuple.Create(SymbolEnum.NEG,"NEG"),
Tuple.Create(SymbolEnum.s,"s"),
Tuple.Create(SymbolEnum.bracket_elem,"bracket_elem"),
Tuple.Create(SymbolEnum.bracket,"bracket"),
Tuple.Create(SymbolEnum.rep,"rep"),
Tuple.Create(SymbolEnum.atom_expr,"atom_expr"),
Tuple.Create(SymbolEnum.expr,"expr"),
Tuple.Create(SymbolEnum.expr_concat,"expr_concat"),
Tuple.Create(SymbolEnum.alt_expr,"alt_expr"),
Tuple.Create(SymbolEnum.__list___merged_bracket_bracket_elem____,"__list___merged_bracket_bracket_elem____"),
Tuple.Create(SymbolEnum.__list___merged_expr_concat_expr____,"__list___merged_expr_concat_expr____"),
Tuple.Create(SymbolEnum.__list___merged_alt_expr_expr_concat____,"__list___merged_alt_expr_expr_concat____"));
return symbols_rep;
}
public Parser<SymbolEnum,object> CreateParser()
{
Parser<SymbolEnum,object> parser = null;
 // Identity functions (x => x) are used directly without storing them in `functions` variables
var __functions_0__ = new Func<object,object>((x) => x); // s, bracket_elem, atom_expr, expr_concat
var __functions_1__ = new Func<char,object,char,object>((min,_1,max) => Tuple.Create(min,max)); // bracket_elem
var __functions_2__ = new Func<object,object,IEnumerable<object>,object,object>((_0,NEG,bracket_elem,_3) => new Bracket(true,bracket_elem.ToArray())); // bracket
var __functions_3__ = new Func<object,IEnumerable<object>,object,object>((_0,bracket_elem,_3) => new Bracket(false,bracket_elem.ToArray())); // bracket
var __functions_4__ = new Func<object>(() => Repetition.Create(1,1)); // rep
var __functions_5__ = new Func<object,object>((_0) => Repetition.Create(0,1)); // rep
var __functions_6__ = new Func<object,object>((_0) => Repetition.CreateWithMin(1)); // rep
var __functions_7__ = new Func<object,object>((_0) => Repetition.CreateWithMin(0)); // rep
var __functions_8__ = new Func<object,int,object,object>((_0,NUM,_2) => Repetition.Create(NUM,NUM)); // rep
var __functions_9__ = new Func<object,int,object,int,object,object>((_0,min,_2,max,_4) => Repetition.Create(min,max)); // rep
var __functions_10__ = new Func<object,int,object,object,object>((_0,NUM,_2,_3) => Repetition.CreateWithMin(NUM)); // rep
var __functions_11__ = new Func<object,object,int,object,object>((_0,_1,NUM,_3) => Repetition.CreateWithMax(NUM)); // rep
var __functions_12__ = new Func<object,object>((CLASS) => new Bracket(false,CLASS)); // atom_expr
var __functions_13__ = new Func<object,object>((_0) => new Bracket(true,'\n')); // atom_expr
var __functions_14__ = new Func<object,AltRegex,object,object>((_0,alt_expr,_2) => alt_expr); // atom_expr
var __functions_15__ = new Func<object,Repetition,object>((atom_expr,rep) => new RegexElem(atom_expr,rep)); // expr
var __functions_16__ = new Func<IEnumerable<List<RegexElem>>,object>((expr_concat) => new AltRegex(expr_concat)); // alt_expr
var __functions_17__ = new Func<object,object>((bracket_elem) => new List<object>(new List<object>{bracket_elem})); // __list___merged_bracket_bracket_elem____
var __functions_18__ = new Func<List<object>,object,object>((list,bracket_elem) => {list.Add(bracket_elem);return list;}); // __list___merged_bracket_bracket_elem____
var __functions_19__ = new Func<RegexElem,object>((expr) => new List<RegexElem>(new List<RegexElem>{expr})); // __list___merged_expr_concat_expr____
var __functions_20__ = new Func<List<RegexElem>,RegexElem,object>((list,expr) => {list.Add(expr);return list;}); // __list___merged_expr_concat_expr____
var __functions_21__ = new Func<List<RegexElem>,object>((expr_concat) => new List<List<RegexElem>>(new List<List<RegexElem>>{expr_concat})); // __list___merged_alt_expr_expr_concat____
var __functions_22__ = new Func<List<List<RegexElem>>,object,List<RegexElem>,object>((list,_1,expr_concat) => {list.Add(expr_concat);return list;}); // __list___merged_alt_expr_expr_concat____
var __actions_table__ = new IEnumerable<ParseAction<SymbolEnum,object>>[43,30];__actions_table__[0,2] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(true)};__actions_table__[1,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.s,
1,
null,
-1,
"Action for \"s\" at (111,12)",
null,
ProductionAction<object>.Convert(new Func<AltRegex,object>((alt_expr) => __functions_0__(alt_expr)),0))
))};__actions_table__[2,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.alt_expr,
1,
null,
-1,
"Action for \"alt_expr\" at (157,14)",
null,
ProductionAction<object>.Convert(new Func<List<List<RegexElem>>,object>((__merged_alt_expr_expr_concat__) => __functions_16__(__merged_alt_expr_expr_concat__)),0))
))};__actions_table__[3,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_alt_expr_expr_concat____,
1,
null,
-1,
"Action for \"__list___merged_alt_expr_expr_concat____\" at (157,14)",
null,
ProductionAction<object>.Convert(new Func<List<RegexElem>,object>((expr_concat) => __functions_21__(expr_concat)),0))
))};__actions_table__[4,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.expr_concat,
1,
null,
-1,
"Action for \"expr_concat\" at (154,33)",
null,
ProductionAction<object>.Convert(new Func<List<RegexElem>,object>((__merged_expr_concat_expr__) => __functions_0__(__merged_expr_concat_expr__)),0))
))};__actions_table__[5,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_expr_concat_expr____,
1,
null,
-1,
"Action for \"__list___merged_expr_concat_expr____\" at (154,33)",
null,
ProductionAction<object>.Convert(new Func<RegexElem,object>((expr) => __functions_19__(expr)),0))
))};__actions_table__[6,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
0,
null,
-1,
"Action for \"rep\" at (124,18)",
null,
ProductionAction<object>.Convert(new Func<object>(() => __functions_4__()),0))
))};__actions_table__[7,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.atom_expr,
1,
null,
-1,
"Action for \"atom_expr\" at (141,15)",
null,
ProductionAction<object>.Convert(new Func<Bracket,object>((bracket) => __functions_0__(bracket)),0))
))};__actions_table__[9,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.atom_expr,
1,
null,
-1,
"Action for \"atom_expr\" at (142,15)",
null,
ProductionAction<object>.Convert(new Func<char,object>((CHAR) => __functions_0__(CHAR)),0))
))};__actions_table__[10,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.atom_expr,
1,
null,
-1,
"Action for \"atom_expr\" at (143,15)",
null,
ProductionAction<object>.Convert(new Func<object,object>((CLASS) => __functions_12__(CLASS)),0))
))};__actions_table__[11,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.atom_expr,
1,
null,
-1,
"Action for \"atom_expr\" at (145,27)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_13__(_0)),1))
))};__actions_table__[14,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_expr_concat_expr____,
2,
null,
-1,
"Action for \"__list___merged_expr_concat_expr____\" at (154,33)",
null,
ProductionAction<object>.Convert(new Func<List<RegexElem>,RegexElem,object>((list,expr) => __functions_20__(list,expr)),0))
))};__actions_table__[15,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.expr,
2,
null,
-1,
"Action for \"expr\" at (150,10)",
null,
ProductionAction<object>.Convert(new Func<object,Repetition,object>((atom_expr,rep) => __functions_15__(atom_expr,rep)),0))
))};__actions_table__[16,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
1,
null,
-1,
"Action for \"rep\" at (125,35)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_5__(_0)),1))
))};__actions_table__[17,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
1,
null,
-1,
"Action for \"rep\" at (127,35)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_6__(_0)),1))
))};__actions_table__[18,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
1,
null,
-1,
"Action for \"rep\" at (129,35)",
null,
ProductionAction<object>.Convert(new Func<object,object>((_0) => __functions_7__(_0)),1))
))};__actions_table__[22,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_bracket_bracket_elem____,
1,
null,
-1,
"Action for \"__list___merged_bracket_bracket_elem____\" at (119,34)",
null,
ProductionAction<object>.Convert(new Func<object,object>((bracket_elem) => __functions_17__(bracket_elem)),0))
))};__actions_table__[23,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.bracket_elem,
1,
null,
-1,
"Action for \"bracket_elem\" at (113,17)",
null,
ProductionAction<object>.Convert(new Func<char,object>((CHAR) => __functions_0__(CHAR)),0))
))};__actions_table__[24,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.bracket_elem,
1,
null,
-1,
"Action for \"bracket_elem\" at (114,17)",
null,
ProductionAction<object>.Convert(new Func<object,object>((CLASS) => __functions_0__(CLASS)),0))
))};__actions_table__[26,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_alt_expr_expr_concat____,
3,
null,
-1,
"Action for \"__list___merged_alt_expr_expr_concat____\" at (157,14)",
null,
ProductionAction<object>.Convert(new Func<List<List<RegexElem>>,object,List<RegexElem>,object>((list,_1,expr_concat) => __functions_22__(list,_1,expr_concat)),0))
))};__actions_table__[30,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.bracket,
3,
null,
-1,
"Action for \"bracket\" at (119,20)",
null,
ProductionAction<object>.Convert(new Func<object,List<object>,object,object>((_0,__merged_bracket_bracket_elem__,_3) => __functions_3__(_0,__merged_bracket_bracket_elem__,_3)),1))
))};__actions_table__[31,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_bracket_bracket_elem____,
2,
null,
-1,
"Action for \"__list___merged_bracket_bracket_elem____\" at (119,34)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object,object>((list,bracket_elem) => __functions_18__(list,bracket_elem)),0))
))};__actions_table__[33,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.atom_expr,
3,
null,
-1,
"Action for \"atom_expr\" at (147,27)",
null,
ProductionAction<object>.Convert(new Func<object,AltRegex,object,object>((_0,alt_expr,_2) => __functions_14__(_0,alt_expr,_2)),1))
))};__actions_table__[34,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
3,
null,
-1,
"Action for \"rep\" at (131,35)",
null,
ProductionAction<object>.Convert(new Func<object,int,object,object>((_0,NUM,_2) => __functions_8__(_0,NUM,_2)),1))
))};__actions_table__[37,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.bracket,
4,
null,
-1,
"Action for \"bracket\" at (119,20)",
null,
ProductionAction<object>.Convert(new Func<object,object,List<object>,object,object>((_0,NEG,__merged_bracket_bracket_elem__,_3) => __functions_2__(_0,NEG,__merged_bracket_bracket_elem__,_3)),1))
))};__actions_table__[38,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.bracket_elem,
3,
null,
-1,
"Action for \"bracket_elem\" at (115,29)",
null,
ProductionAction<object>.Convert(new Func<char,object,char,object>((min,_1,max) => __functions_1__(min,_1,max)),0))
))};__actions_table__[40,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
4,
null,
-1,
"Action for \"rep\" at (135,35)",
null,
ProductionAction<object>.Convert(new Func<object,int,object,object,object>((_0,NUM,_2,_3) => __functions_10__(_0,NUM,_2,_3)),1))
))};__actions_table__[41,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
4,
null,
-1,
"Action for \"rep\" at (137,35)",
null,
ProductionAction<object>.Convert(new Func<object,object,int,object,object>((_0,_1,NUM,_3) => __functions_11__(_0,_1,NUM,_3)),2))
))};__actions_table__[42,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.rep,
5,
null,
-1,
"Action for \"rep\" at (133,35)",
null,
ProductionAction<object>.Convert(new Func<object,int,object,int,object,object>((_0,min,_2,max,_4) => __functions_9__(_0,min,_2,max,_4)),1))
))};
actionsTableDuplicates0(__actions_table__);
var __edges_table__ = ActionTableData<SymbolEnum,object>.CreateEdgesTable(43,30);
createEdges0(__edges_table__);
var __recovery_table__ = createRecoveryTable();
var symbols_rep = createSymbolsRep();
parser = new Parser<SymbolEnum,object>(new ActionTableData<SymbolEnum,object>(
actionsTable:__actions_table__,edgesTable:__edges_table__,recoveryTable:__recovery_table__,startSymbol:SymbolEnum.s,eofSymbol:SymbolEnum.EOF,syntaxErrorSymbol:SymbolEnum.Error,lookaheadWidth:1),symbols_rep);
return parser;
}

public static void actionsTableDuplicates0(IEnumerable<ParseAction<SymbolEnum,object>>[,] __actions_table__)
{
__actions_table__[0,11] = __actions_table__[0,2];
__actions_table__[0,13] = __actions_table__[0,2];
__actions_table__[0,15] = __actions_table__[0,2];
__actions_table__[0,16] = __actions_table__[0,2];
__actions_table__[2,12] = __actions_table__[0,2];
__actions_table__[2,14] = __actions_table__[2,1];
__actions_table__[3,12] = __actions_table__[3,1];
__actions_table__[3,14] = __actions_table__[3,1];
__actions_table__[4,2] = __actions_table__[0,2];
__actions_table__[4,11] = __actions_table__[0,2];
__actions_table__[4,12] = __actions_table__[4,1];
__actions_table__[4,13] = __actions_table__[0,2];
__actions_table__[4,14] = __actions_table__[4,1];
__actions_table__[4,15] = __actions_table__[0,2];
__actions_table__[4,16] = __actions_table__[0,2];
__actions_table__[5,2] = __actions_table__[5,1];
__actions_table__[5,11] = __actions_table__[5,1];
__actions_table__[5,12] = __actions_table__[5,1];
__actions_table__[5,13] = __actions_table__[5,1];
__actions_table__[5,14] = __actions_table__[5,1];
__actions_table__[5,15] = __actions_table__[5,1];
__actions_table__[5,16] = __actions_table__[5,1];
__actions_table__[6,2] = __actions_table__[6,1];
__actions_table__[6,4] = __actions_table__[0,2];
__actions_table__[6,8] = __actions_table__[0,2];
__actions_table__[6,9] = __actions_table__[0,2];
__actions_table__[6,10] = __actions_table__[0,2];
__actions_table__[6,11] = __actions_table__[6,1];
__actions_table__[6,12] = __actions_table__[6,1];
__actions_table__[6,13] = __actions_table__[6,1];
__actions_table__[6,14] = __actions_table__[6,1];
__actions_table__[6,15] = __actions_table__[6,1];
__actions_table__[6,16] = __actions_table__[6,1];
__actions_table__[7,2] = __actions_table__[7,1];
__actions_table__[7,4] = __actions_table__[7,1];
__actions_table__[7,8] = __actions_table__[7,1];
__actions_table__[7,9] = __actions_table__[7,1];
__actions_table__[7,10] = __actions_table__[7,1];
__actions_table__[7,11] = __actions_table__[7,1];
__actions_table__[7,12] = __actions_table__[7,1];
__actions_table__[7,13] = __actions_table__[7,1];
__actions_table__[7,14] = __actions_table__[7,1];
__actions_table__[7,15] = __actions_table__[7,1];
__actions_table__[7,16] = __actions_table__[7,1];
__actions_table__[8,15] = __actions_table__[0,2];
__actions_table__[8,16] = __actions_table__[0,2];
__actions_table__[8,18] = __actions_table__[0,2];
__actions_table__[9,2] = __actions_table__[9,1];
__actions_table__[9,4] = __actions_table__[9,1];
__actions_table__[9,8] = __actions_table__[9,1];
__actions_table__[9,9] = __actions_table__[9,1];
__actions_table__[9,10] = __actions_table__[9,1];
__actions_table__[9,11] = __actions_table__[9,1];
__actions_table__[9,12] = __actions_table__[9,1];
__actions_table__[9,13] = __actions_table__[9,1];
__actions_table__[9,14] = __actions_table__[9,1];
__actions_table__[9,15] = __actions_table__[9,1];
__actions_table__[9,16] = __actions_table__[9,1];
__actions_table__[10,2] = __actions_table__[10,1];
__actions_table__[10,4] = __actions_table__[10,1];
__actions_table__[10,8] = __actions_table__[10,1];
__actions_table__[10,9] = __actions_table__[10,1];
__actions_table__[10,10] = __actions_table__[10,1];
__actions_table__[10,11] = __actions_table__[10,1];
__actions_table__[10,12] = __actions_table__[10,1];
__actions_table__[10,13] = __actions_table__[10,1];
__actions_table__[10,14] = __actions_table__[10,1];
__actions_table__[10,15] = __actions_table__[10,1];
__actions_table__[10,16] = __actions_table__[10,1];
__actions_table__[11,2] = __actions_table__[11,1];
__actions_table__[11,4] = __actions_table__[11,1];
__actions_table__[11,8] = __actions_table__[11,1];
__actions_table__[11,9] = __actions_table__[11,1];
__actions_table__[11,10] = __actions_table__[11,1];
__actions_table__[11,11] = __actions_table__[11,1];
__actions_table__[11,12] = __actions_table__[11,1];
__actions_table__[11,13] = __actions_table__[11,1];
__actions_table__[11,14] = __actions_table__[11,1];
__actions_table__[11,15] = __actions_table__[11,1];
__actions_table__[11,16] = __actions_table__[11,1];
__actions_table__[12,2] = __actions_table__[0,2];
__actions_table__[12,11] = __actions_table__[0,2];
__actions_table__[12,13] = __actions_table__[0,2];
__actions_table__[12,15] = __actions_table__[0,2];
__actions_table__[12,16] = __actions_table__[0,2];
__actions_table__[13,2] = __actions_table__[0,2];
__actions_table__[13,11] = __actions_table__[0,2];
__actions_table__[13,13] = __actions_table__[0,2];
__actions_table__[13,15] = __actions_table__[0,2];
__actions_table__[13,16] = __actions_table__[0,2];
__actions_table__[14,2] = __actions_table__[14,1];
__actions_table__[14,11] = __actions_table__[14,1];
__actions_table__[14,12] = __actions_table__[14,1];
__actions_table__[14,13] = __actions_table__[14,1];
__actions_table__[14,14] = __actions_table__[14,1];
__actions_table__[14,15] = __actions_table__[14,1];
__actions_table__[14,16] = __actions_table__[14,1];
__actions_table__[15,2] = __actions_table__[15,1];
__actions_table__[15,11] = __actions_table__[15,1];
__actions_table__[15,12] = __actions_table__[15,1];
__actions_table__[15,13] = __actions_table__[15,1];
__actions_table__[15,14] = __actions_table__[15,1];
__actions_table__[15,15] = __actions_table__[15,1];
__actions_table__[15,16] = __actions_table__[15,1];
__actions_table__[16,2] = __actions_table__[16,1];
__actions_table__[16,11] = __actions_table__[16,1];
__actions_table__[16,12] = __actions_table__[16,1];
__actions_table__[16,13] = __actions_table__[16,1];
__actions_table__[16,14] = __actions_table__[16,1];
__actions_table__[16,15] = __actions_table__[16,1];
__actions_table__[16,16] = __actions_table__[16,1];
__actions_table__[17,2] = __actions_table__[17,1];
__actions_table__[17,11] = __actions_table__[17,1];
__actions_table__[17,12] = __actions_table__[17,1];
__actions_table__[17,13] = __actions_table__[17,1];
__actions_table__[17,14] = __actions_table__[17,1];
__actions_table__[17,15] = __actions_table__[17,1];
__actions_table__[17,16] = __actions_table__[17,1];
__actions_table__[18,2] = __actions_table__[18,1];
__actions_table__[18,11] = __actions_table__[18,1];
__actions_table__[18,12] = __actions_table__[18,1];
__actions_table__[18,13] = __actions_table__[18,1];
__actions_table__[18,14] = __actions_table__[18,1];
__actions_table__[18,15] = __actions_table__[18,1];
__actions_table__[18,16] = __actions_table__[18,1];
__actions_table__[19,6] = __actions_table__[0,2];
__actions_table__[19,7] = __actions_table__[0,2];
__actions_table__[20,15] = __actions_table__[0,2];
__actions_table__[20,16] = __actions_table__[0,2];
__actions_table__[21,3] = __actions_table__[0,2];
__actions_table__[21,15] = __actions_table__[0,2];
__actions_table__[21,16] = __actions_table__[0,2];
__actions_table__[22,15] = __actions_table__[22,3];
__actions_table__[22,16] = __actions_table__[22,3];
__actions_table__[23,15] = __actions_table__[23,3];
__actions_table__[23,16] = __actions_table__[23,3];
__actions_table__[23,17] = __actions_table__[0,2];
__actions_table__[24,15] = __actions_table__[24,3];
__actions_table__[24,16] = __actions_table__[24,3];
__actions_table__[25,14] = __actions_table__[0,2];
__actions_table__[26,12] = __actions_table__[26,1];
__actions_table__[26,14] = __actions_table__[26,1];
__actions_table__[27,5] = __actions_table__[0,2];
__actions_table__[27,6] = __actions_table__[0,2];
__actions_table__[28,7] = __actions_table__[0,2];
__actions_table__[29,3] = __actions_table__[0,2];
__actions_table__[29,15] = __actions_table__[0,2];
__actions_table__[29,16] = __actions_table__[0,2];
__actions_table__[30,2] = __actions_table__[30,1];
__actions_table__[30,4] = __actions_table__[30,1];
__actions_table__[30,8] = __actions_table__[30,1];
__actions_table__[30,9] = __actions_table__[30,1];
__actions_table__[30,10] = __actions_table__[30,1];
__actions_table__[30,11] = __actions_table__[30,1];
__actions_table__[30,12] = __actions_table__[30,1];
__actions_table__[30,13] = __actions_table__[30,1];
__actions_table__[30,14] = __actions_table__[30,1];
__actions_table__[30,15] = __actions_table__[30,1];
__actions_table__[30,16] = __actions_table__[30,1];
__actions_table__[31,15] = __actions_table__[31,3];
__actions_table__[31,16] = __actions_table__[31,3];
__actions_table__[32,16] = __actions_table__[0,2];
__actions_table__[33,2] = __actions_table__[33,1];
__actions_table__[33,4] = __actions_table__[33,1];
__actions_table__[33,8] = __actions_table__[33,1];
__actions_table__[33,9] = __actions_table__[33,1];
__actions_table__[33,10] = __actions_table__[33,1];
__actions_table__[33,11] = __actions_table__[33,1];
__actions_table__[33,12] = __actions_table__[33,1];
__actions_table__[33,13] = __actions_table__[33,1];
__actions_table__[33,14] = __actions_table__[33,1];
__actions_table__[33,15] = __actions_table__[33,1];
__actions_table__[33,16] = __actions_table__[33,1];
__actions_table__[34,2] = __actions_table__[34,1];
__actions_table__[34,11] = __actions_table__[34,1];
__actions_table__[34,12] = __actions_table__[34,1];
__actions_table__[34,13] = __actions_table__[34,1];
__actions_table__[34,14] = __actions_table__[34,1];
__actions_table__[34,15] = __actions_table__[34,1];
__actions_table__[34,16] = __actions_table__[34,1];
__actions_table__[35,5] = __actions_table__[0,2];
__actions_table__[35,7] = __actions_table__[0,2];
__actions_table__[36,5] = __actions_table__[0,2];
__actions_table__[37,2] = __actions_table__[37,1];
__actions_table__[37,4] = __actions_table__[37,1];
__actions_table__[37,8] = __actions_table__[37,1];
__actions_table__[37,9] = __actions_table__[37,1];
__actions_table__[37,10] = __actions_table__[37,1];
__actions_table__[37,11] = __actions_table__[37,1];
__actions_table__[37,12] = __actions_table__[37,1];
__actions_table__[37,13] = __actions_table__[37,1];
__actions_table__[37,14] = __actions_table__[37,1];
__actions_table__[37,15] = __actions_table__[37,1];
__actions_table__[37,16] = __actions_table__[37,1];
__actions_table__[38,15] = __actions_table__[38,3];
__actions_table__[38,16] = __actions_table__[38,3];
__actions_table__[39,5] = __actions_table__[0,2];
__actions_table__[40,2] = __actions_table__[40,1];
__actions_table__[40,11] = __actions_table__[40,1];
__actions_table__[40,12] = __actions_table__[40,1];
__actions_table__[40,13] = __actions_table__[40,1];
__actions_table__[40,14] = __actions_table__[40,1];
__actions_table__[40,15] = __actions_table__[40,1];
__actions_table__[40,16] = __actions_table__[40,1];
__actions_table__[41,2] = __actions_table__[41,1];
__actions_table__[41,11] = __actions_table__[41,1];
__actions_table__[41,12] = __actions_table__[41,1];
__actions_table__[41,13] = __actions_table__[41,1];
__actions_table__[41,14] = __actions_table__[41,1];
__actions_table__[41,15] = __actions_table__[41,1];
__actions_table__[41,16] = __actions_table__[41,1];
__actions_table__[42,2] = __actions_table__[42,1];
__actions_table__[42,11] = __actions_table__[42,1];
__actions_table__[42,12] = __actions_table__[42,1];
__actions_table__[42,13] = __actions_table__[42,1];
__actions_table__[42,14] = __actions_table__[42,1];
__actions_table__[42,15] = __actions_table__[42,1];
__actions_table__[42,16] = __actions_table__[42,1];
}
}
}
