/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "NaiveLanguageTools.MultiRegex/RegexParser/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace NaiveLanguageTools.MultiRegex.RegexParser
{
public enum SymbolEnum
{
Error,
EOF,
LBRACKET,
RBRACKET,
LBRACE,
RBRACE,
COMMA,
NUM,
PLUS,
ASTERISK,
QMARK,
DOT,
OR,
LPAREN,
RPAREN,
CLASS,
CHAR,
MINUS,
NEG,
s,
bracket_elem,
bracket,
rep,
atom_expr,
expr,
expr_concat,
alt_expr,
__list___merged_bracket_bracket_elem____,
__list___merged_expr_concat_expr____,
__list___merged_alt_expr_expr_concat____
}
}
