/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "Readers/PBXProj/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System.Collections.Generic;
using System.Linq;
using System;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace PBXProj
{
public partial class ParserFactory
{

public static void createEdges0(int[,] __edges_table__)
{
__edges_table__[0,3] = 2;
__edges_table__[0,13] = 1;
__edges_table__[2,10] = 6;
__edges_table__[2,12] = 5;
__edges_table__[2,18] = 4;
__edges_table__[2,19] = 3;
__edges_table__[3,6] = 7;
__edges_table__[4,10] = 6;
__edges_table__[4,12] = 8;
__edges_table__[6,7] = 9;
__edges_table__[9,2] = 11;
__edges_table__[9,3] = 2;
__edges_table__[9,4] = 14;
__edges_table__[9,10] = 10;
__edges_table__[9,13] = 12;
__edges_table__[9,14] = 13;
__edges_table__[10,8] = 15;
__edges_table__[11,8] = 16;
__edges_table__[12,8] = 17;
__edges_table__[13,8] = 18;
__edges_table__[14,2] = 23;
__edges_table__[14,3] = 2;
__edges_table__[14,10] = 26;
__edges_table__[14,13] = 28;
__edges_table__[14,15] = 20;
__edges_table__[14,16] = 19;
__edges_table__[14,17] = 21;
__edges_table__[14,20] = 25;
__edges_table__[14,21] = 24;
__edges_table__[14,22] = 22;
__edges_table__[14,23] = 27;
__edges_table__[19,5] = 29;
__edges_table__[20,5] = 30;
__edges_table__[21,5] = 31;
__edges_table__[22,9] = 32;
__edges_table__[25,9] = 33;
__edges_table__[27,9] = 34;
__edges_table__[32,2] = 35;
__edges_table__[33,10] = 36;
__edges_table__[34,3] = 2;
__edges_table__[34,13] = 37;
}
public static IEnumerable<NfaCell<TokenEnum, object>>[,] createRecoveryTable()
{
var __recovery_table__ = new IEnumerable<NfaCell<TokenEnum,object>>[38,24];
return __recovery_table__;
}
public static StringRep<TokenEnum> createSymbolsRep()
{
var symbols_rep = StringRep.Create(Tuple.Create(TokenEnum.Error,"Error"),
Tuple.Create(TokenEnum.EOF,"EOF"),
Tuple.Create(TokenEnum.STR,"STR"),
Tuple.Create(TokenEnum.LBRACE,"LBRACE"),
Tuple.Create(TokenEnum.LPAREN,"LPAREN"),
Tuple.Create(TokenEnum.RPAREN,"RPAREN"),
Tuple.Create(TokenEnum.RBRACE,"RBRACE"),
Tuple.Create(TokenEnum.EQ,"EQ"),
Tuple.Create(TokenEnum.SEMI,"SEMI"),
Tuple.Create(TokenEnum.COMMA,"COMMA"),
Tuple.Create(TokenEnum.ID,"ID"),
Tuple.Create(TokenEnum.proj,"proj"),
Tuple.Create(TokenEnum.pair,"pair"),
Tuple.Create(TokenEnum.dict,"dict"),
Tuple.Create(TokenEnum.list,"list"),
Tuple.Create(TokenEnum.id_list,"id_list"),
Tuple.Create(TokenEnum.str_list,"str_list"),
Tuple.Create(TokenEnum.dict_list,"dict_list"),
Tuple.Create(TokenEnum.__list___merged_dict_pair____,"__list___merged_dict_pair____"),
Tuple.Create(TokenEnum.__optList___merged_dict_pair____,"__optList___merged_dict_pair____"),
Tuple.Create(TokenEnum.__list___merged_id_list_ID____,"__list___merged_id_list_ID____"),
Tuple.Create(TokenEnum.__optList___merged_id_list_ID____,"__optList___merged_id_list_ID____"),
Tuple.Create(TokenEnum.__list___merged_str_list_STR____,"__list___merged_str_list_STR____"),
Tuple.Create(TokenEnum.__list___merged_dict_list_dict____,"__list___merged_dict_list_dict____"));
return symbols_rep;
}
public Parser<TokenEnum,object> CreateParser()
{
Parser<TokenEnum,object> parser = null;
 // Identity functions (x => x) are used directly without storing them in `functions` variables
var __functions_0__ = new Func<object,object>((x) => x); // proj, id_list, str_list, dict_list, __optList___merged_dict_pair____, __optList___merged_id_list_ID____
var __functions_1__ = new Func<string,object,string,object,object>((id,_1,val,_6) => Tuple.Create(id,(object)val)); // pair
var __functions_2__ = new Func<string,object,object,object,object>((id,_1,val,_6) => Tuple.Create(id,(object)val)); // pair
var __functions_3__ = new Func<object,IEnumerable<Tuple<string,object>>,object,object>((_0,pair,_2) => pair.ToDictionary(it => it.Item1,it => it.Item2)); // dict
var __functions_4__ = new Func<object,object,object,object>((_0,l,_4) => l); // list
var __functions_5__ = new Func<Tuple<string,object>,object>((pair) => new List<Tuple<string,object>>(new List<Tuple<string,object>>{pair})); // __list___merged_dict_pair____
var __functions_6__ = new Func<List<Tuple<string,object>>,Tuple<string,object>,object>((list,pair) => {list.Add(pair);return list;}); // __list___merged_dict_pair____
var __functions_7__ = new Func<object>(() => new List<Tuple<string,object>>(new List<Tuple<string,object>>{})); // __optList___merged_dict_pair____
var __functions_8__ = new Func<string,object>((ID) => new List<string>(new List<string>{ID})); // __list___merged_id_list_ID____
var __functions_9__ = new Func<List<string>,object,string,object>((list,_1,ID) => {list.Add(ID);return list;}); // __list___merged_id_list_ID____
var __functions_10__ = new Func<object>(() => new List<string>(new List<string>{})); // __optList___merged_id_list_ID____
var __functions_11__ = new Func<object,object>((STR) => new List<object>(new List<object>{STR})); // __list___merged_str_list_STR____
var __functions_12__ = new Func<List<object>,object,object,object>((list,_1,STR) => {list.Add(STR);return list;}); // __list___merged_str_list_STR____
var __functions_13__ = new Func<object,object>((dict) => new List<object>(new List<object>{dict})); // __list___merged_dict_list_dict____
var __functions_14__ = new Func<List<object>,object,object,object>((list,_1,dict) => {list.Add(dict);return list;}); // __list___merged_dict_list_dict____
var __actions_table__ = new IEnumerable<ParseAction<TokenEnum,object>>[38,24];__actions_table__[0,3] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(true)};__actions_table__[1,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.proj,
1,
null,
-1,
"Action for \"proj\" at (124,9)",
null,
ProductionAction<object>.Convert(new Func<object,object>((dict) => __functions_0__(dict)),0))
))};__actions_table__[2,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__optList___merged_dict_pair____,
0,
null,
-1,
"Action for \"__optList___merged_dict_pair____\" at (130,17)",
null,
ProductionAction<object>.Convert(new Func<object>(() => __functions_7__()),0))
))};__actions_table__[4,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__optList___merged_dict_pair____,
1,
null,
-1,
"Action for \"__optList___merged_dict_pair____\" at (130,17)",
null,
ProductionAction<object>.Convert(new Func<List<Tuple<string,object>>,object>((obj) => __functions_0__(obj)),0))
))};__actions_table__[5,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_dict_pair____,
1,
null,
-1,
"Action for \"__list___merged_dict_pair____\" at (130,17)",
null,
ProductionAction<object>.Convert(new Func<Tuple<string,object>,object>((pair) => __functions_5__(pair)),0))
))};__actions_table__[7,1] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.dict,
3,
null,
-1,
"Action for \"dict\" at (130,10)",
null,
ProductionAction<object>.Convert(new Func<object,List<Tuple<string,object>>,object,object>((_0,__merged_dict_pair__,_2) => __functions_3__(_0,__merged_dict_pair__,_2)),1))
))};__actions_table__[8,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_dict_pair____,
2,
null,
-1,
"Action for \"__list___merged_dict_pair____\" at (130,17)",
null,
ProductionAction<object>.Convert(new Func<List<Tuple<string,object>>,Tuple<string,object>,object>((list,pair) => __functions_6__(list,pair)),0))
))};__actions_table__[14,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__optList___merged_id_list_ID____,
0,
null,
-1,
"Action for \"__optList___merged_id_list_ID____\" at (136,12)",
null,
ProductionAction<object>.Convert(new Func<object>(() => __functions_10__()),0))
))};__actions_table__[15,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.pair,
4,
null,
-1,
"Action for \"pair\" at (127,31)",
null,
ProductionAction<object>.Convert(new Func<string,object,string,object,object>((id,_1,val,_6) => __functions_1__(id,_1,val,_6)),0))
))};__actions_table__[16,6] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.pair,
4,
null,
-1,
"Action for \"pair\" at (127,31)",
null,
ProductionAction<object>.Convert(new Func<string,object,object,object,object>((id,_1,val,_6) => __functions_2__(id,_1,val,_6)),0))
))};__actions_table__[22,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.str_list,
1,
null,
-1,
"Action for \"str_list\" at (139,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object>((__merged_str_list_STR__) => __functions_0__(__merged_str_list_STR__)),0))
))};__actions_table__[23,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_str_list_STR____,
1,
null,
-1,
"Action for \"__list___merged_str_list_STR____\" at (139,13)",
null,
ProductionAction<object>.Convert(new Func<object,object>((STR) => __functions_11__(STR)),0))
))};__actions_table__[24,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.id_list,
1,
null,
-1,
"Action for \"id_list\" at (136,12)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object>((__merged_id_list_ID__) => __functions_0__(__merged_id_list_ID__)),0))
))};__actions_table__[25,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__optList___merged_id_list_ID____,
1,
null,
-1,
"Action for \"__optList___merged_id_list_ID____\" at (136,12)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object>((obj) => __functions_0__(obj)),0))
))};__actions_table__[26,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_id_list_ID____,
1,
null,
-1,
"Action for \"__list___merged_id_list_ID____\" at (136,12)",
null,
ProductionAction<object>.Convert(new Func<string,object>((ID) => __functions_8__(ID)),0))
))};__actions_table__[27,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.dict_list,
1,
null,
-1,
"Action for \"dict_list\" at (142,15)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object>((__merged_dict_list_dict__) => __functions_0__(__merged_dict_list_dict__)),0))
))};__actions_table__[28,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_dict_list_dict____,
1,
null,
-1,
"Action for \"__list___merged_dict_list_dict____\" at (142,15)",
null,
ProductionAction<object>.Convert(new Func<object,object>((dict) => __functions_13__(dict)),0))
))};__actions_table__[29,8] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.list,
3,
null,
-1,
"Action for \"list\" at (133,10)",
null,
ProductionAction<object>.Convert(new Func<object,object,object,object>((_0,l,_4) => __functions_4__(_0,l,_4)),1))
))};__actions_table__[35,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_str_list_STR____,
3,
null,
-1,
"Action for \"__list___merged_str_list_STR____\" at (139,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object,object,object>((list,_1,STR) => __functions_12__(list,_1,STR)),0))
))};__actions_table__[36,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_id_list_ID____,
3,
null,
-1,
"Action for \"__list___merged_id_list_ID____\" at (136,12)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object,string,object>((list,_1,ID) => __functions_9__(list,_1,ID)),0))
))};__actions_table__[37,5] = new ParseAction<TokenEnum,object>[]{new ParseAction<TokenEnum,object>(false,ReductionAction.Create(NfaCell<TokenEnum,object>.Create(
TokenEnum.__list___merged_dict_list_dict____,
3,
null,
-1,
"Action for \"__list___merged_dict_list_dict____\" at (142,15)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object,object,object>((list,_1,dict) => __functions_14__(list,_1,dict)),0))
))};
actionsTableDuplicates0(__actions_table__);
var __edges_table__ = ActionTableData<TokenEnum,object>.CreateEdgesTable(38,24);
createEdges0(__edges_table__);
var __recovery_table__ = createRecoveryTable();
var symbols_rep = createSymbolsRep();
parser = new Parser<TokenEnum,object>(new ActionTableData<TokenEnum,object>(
actionsTable:__actions_table__,edgesTable:__edges_table__,recoveryTable:__recovery_table__,startSymbol:TokenEnum.proj,eofSymbol:TokenEnum.EOF,syntaxErrorSymbol:TokenEnum.Error,lookaheadWidth:1),symbols_rep);
return parser;
}

public static void actionsTableDuplicates0(IEnumerable<ParseAction<TokenEnum,object>>[,] __actions_table__)
{
__actions_table__[2,10] = __actions_table__[0,3];
__actions_table__[3,6] = __actions_table__[0,3];
__actions_table__[4,10] = __actions_table__[0,3];
__actions_table__[5,10] = __actions_table__[5,6];
__actions_table__[6,7] = __actions_table__[0,3];
__actions_table__[7,5] = __actions_table__[7,1];
__actions_table__[7,8] = __actions_table__[7,1];
__actions_table__[7,9] = __actions_table__[7,1];
__actions_table__[8,10] = __actions_table__[8,6];
__actions_table__[9,2] = __actions_table__[0,3];
__actions_table__[9,3] = __actions_table__[0,3];
__actions_table__[9,4] = __actions_table__[0,3];
__actions_table__[9,10] = __actions_table__[0,3];
__actions_table__[10,8] = __actions_table__[0,3];
__actions_table__[11,8] = __actions_table__[0,3];
__actions_table__[12,8] = __actions_table__[0,3];
__actions_table__[13,8] = __actions_table__[0,3];
__actions_table__[14,2] = __actions_table__[0,3];
__actions_table__[14,3] = __actions_table__[0,3];
__actions_table__[14,10] = __actions_table__[0,3];
__actions_table__[15,10] = __actions_table__[15,6];
__actions_table__[16,10] = __actions_table__[16,6];
__actions_table__[17,6] = __actions_table__[16,6];
__actions_table__[17,10] = __actions_table__[16,6];
__actions_table__[18,6] = __actions_table__[16,6];
__actions_table__[18,10] = __actions_table__[16,6];
__actions_table__[19,5] = __actions_table__[0,3];
__actions_table__[20,5] = __actions_table__[0,3];
__actions_table__[21,5] = __actions_table__[0,3];
__actions_table__[22,9] = __actions_table__[0,3];
__actions_table__[23,9] = __actions_table__[23,5];
__actions_table__[25,9] = __actions_table__[0,3];
__actions_table__[26,9] = __actions_table__[26,5];
__actions_table__[27,9] = __actions_table__[0,3];
__actions_table__[28,9] = __actions_table__[28,5];
__actions_table__[30,8] = __actions_table__[29,8];
__actions_table__[31,8] = __actions_table__[29,8];
__actions_table__[32,2] = __actions_table__[0,3];
__actions_table__[33,10] = __actions_table__[0,3];
__actions_table__[34,3] = __actions_table__[0,3];
__actions_table__[35,9] = __actions_table__[35,5];
__actions_table__[36,9] = __actions_table__[36,5];
__actions_table__[37,9] = __actions_table__[37,5];
}
}
}
