/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "Readers/PBXProj/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System.Collections.Generic;
using System.Linq;
using System;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace PBXProj
{
public enum TokenEnum
{
Error,
EOF,
STR,
LBRACE,
LPAREN,
RPAREN,
RBRACE,
EQ,
SEMI,
COMMA,
ID,
proj,
pair,
dict,
list,
id_list,
str_list,
dict_list,
__list___merged_dict_pair____,
__optList___merged_dict_pair____,
__list___merged_id_list_ID____,
__optList___merged_id_list_ID____,
__list___merged_str_list_STR____,
__list___merged_dict_list_dict____
}
}
