/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "NaiveLanguageTools.Generator/AST/CodeParser/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace NaiveLanguageTools.Generator.AST.CodeParser
{
public partial class ParserFactory
{

public static void createEdges0(int[,] __edges_table__)
{
__edges_table__[0,8] = 1;
__edges_table__[1,9] = 5;
__edges_table__[1,14] = 3;
__edges_table__[1,16] = 2;
__edges_table__[1,21] = 4;
__edges_table__[2,2] = 13;
__edges_table__[2,3] = 14;
__edges_table__[2,4] = 16;
__edges_table__[2,5] = 17;
__edges_table__[2,6] = 11;
__edges_table__[2,7] = 12;
__edges_table__[2,8] = 15;
__edges_table__[2,9] = 10;
__edges_table__[2,10] = 9;
__edges_table__[2,17] = 6;
__edges_table__[2,23] = 8;
__edges_table__[2,24] = 7;
__edges_table__[3,2] = 18;
__edges_table__[3,4] = 22;
__edges_table__[3,12] = 21;
__edges_table__[3,13] = 19;
__edges_table__[3,20] = 20;
__edges_table__[4,6] = 23;
__edges_table__[8,2] = 28;
__edges_table__[8,3] = 29;
__edges_table__[8,4] = 31;
__edges_table__[8,5] = 32;
__edges_table__[8,6] = 26;
__edges_table__[8,7] = 27;
__edges_table__[8,8] = 30;
__edges_table__[8,9] = 25;
__edges_table__[8,10] = 24;
__edges_table__[18,9] = 5;
__edges_table__[18,14] = 3;
__edges_table__[18,15] = 33;
__edges_table__[18,16] = 35;
__edges_table__[18,21] = 4;
__edges_table__[18,22] = 34;
__edges_table__[20,4] = 22;
__edges_table__[20,12] = 36;
__edges_table__[22,7] = 39;
__edges_table__[22,18] = 38;
__edges_table__[22,19] = 37;
__edges_table__[23,9] = 40;
__edges_table__[33,3] = 41;
__edges_table__[34,7] = 42;
__edges_table__[37,5] = 43;
__edges_table__[38,7] = 44;
__edges_table__[41,4] = 22;
__edges_table__[41,12] = 21;
__edges_table__[41,13] = 45;
__edges_table__[41,20] = 20;
__edges_table__[42,9] = 5;
__edges_table__[42,14] = 3;
__edges_table__[42,16] = 46;
__edges_table__[42,21] = 4;
}
public static IEnumerable<NfaCell<SymbolEnum, object>>[,] createRecoveryTable()
{
var __recovery_table__ = new IEnumerable<NfaCell<SymbolEnum,object>>[47,25];
return __recovery_table__;
}
public static StringRep<SymbolEnum> createSymbolsRep()
{
var symbols_rep = StringRep.Create(Tuple.Create(SymbolEnum.Error,"Error"),
Tuple.Create(SymbolEnum.EOF,"EOF"),
Tuple.Create(SymbolEnum.LANGLE,"LANGLE"),
Tuple.Create(SymbolEnum.RANGLE,"RANGLE"),
Tuple.Create(SymbolEnum.LBRACKET,"LBRACKET"),
Tuple.Create(SymbolEnum.RBRACKET,"RBRACKET"),
Tuple.Create(SymbolEnum.DOT,"DOT"),
Tuple.Create(SymbolEnum.COMMA,"COMMA"),
Tuple.Create(SymbolEnum.NEW,"NEW"),
Tuple.Create(SymbolEnum.IDENTIFIER,"IDENTIFIER"),
Tuple.Create(SymbolEnum.WHATEVER,"WHATEVER"),
Tuple.Create(SymbolEnum.s,"s"),
Tuple.Create(SymbolEnum.array,"array"),
Tuple.Create(SymbolEnum.jagged_array,"jagged_array"),
Tuple.Create(SymbolEnum.dot_identifier,"dot_identifier"),
Tuple.Create(SymbolEnum.typename_list,"typename_list"),
Tuple.Create(SymbolEnum.typename,"typename"),
Tuple.Create(SymbolEnum.whatever,"whatever"),
Tuple.Create(SymbolEnum.__list___merged_array_c____,"__list___merged_array_c____"),
Tuple.Create(SymbolEnum.__optList___merged_array_c____,"__optList___merged_array_c____"),
Tuple.Create(SymbolEnum.__list___merged_jagged_array_a____,"__list___merged_jagged_array_a____"),
Tuple.Create(SymbolEnum.__list___merged_dot_identifier_id____,"__list___merged_dot_identifier_id____"),
Tuple.Create(SymbolEnum.__list___merged_typename_list_t____,"__list___merged_typename_list_t____"),
Tuple.Create(SymbolEnum.__list_s__,"__list_s__"),
Tuple.Create(SymbolEnum.__optList_s__,"__optList_s__"));
return symbols_rep;
}
public Parser<SymbolEnum,object> CreateParser()
{
Parser<SymbolEnum,object> parser = null;
 // Identity functions (x => x) are used directly without storing them in `functions` variables
var __functions_0__ = new Func<object,string,object,object>((_0,t,_2) => t); // s
var __functions_1__ = new Func<object,IEnumerable<object>,object,object>((_0,c,_2) => "["+String.Join("",c)+"]"); // array
var __functions_2__ = new Func<IEnumerable<string>,object>((a) => String.Join("",a)); // jagged_array
var __functions_3__ = new Func<IEnumerable<string>,object>((id) => String.Join(".",id)); // dot_identifier
var __functions_4__ = new Func<IEnumerable<string>,object>((t) => String.Join(",",t)); // typename_list
var __functions_5__ = new Func<string,object,string,object,string,object>((id,l,tt,r,a) => id + l + tt + r + a); // typename
var __functions_6__ = new Func<object,object>((x) => x); // whatever, __optList___merged_array_c____, __optList_s__
var __functions_7__ = new Func<object,object>((c) => new List<object>(new List<object>{c})); // __list___merged_array_c____
var __functions_8__ = new Func<List<object>,object,object>((list,c) => {list.Add(c);return list;}); // __list___merged_array_c____
var __functions_9__ = new Func<object>(() => new List<object>(new List<object>{})); // __optList___merged_array_c____, __optList_s__
var __functions_10__ = new Func<string,object>((a) => new List<string>(new List<string>{a})); // __list___merged_jagged_array_a____
var __functions_11__ = new Func<List<string>,string,object>((list,a) => {list.Add(a);return list;}); // __list___merged_jagged_array_a____
var __functions_12__ = new Func<string,object>((id) => new List<string>(new List<string>{id})); // __list___merged_dot_identifier_id____
var __functions_13__ = new Func<List<string>,object,string,object>((list,_1,id) => {list.Add(id);return list;}); // __list___merged_dot_identifier_id____
var __functions_14__ = new Func<string,object>((t) => new List<string>(new List<string>{t})); // __list___merged_typename_list_t____
var __functions_15__ = new Func<List<string>,object,string,object>((list,_1,t) => {list.Add(t);return list;}); // __list___merged_typename_list_t____
var __functions_16__ = new Func<object,object>((s) => new List<object>(new List<object>{s})); // __list_s__
var __functions_17__ = new Func<List<object>,object,object>((list,s) => {list.Add(s);return list;}); // __list_s__
var __functions_18__ = new Func<string,object>((s) => new List<object>(new List<object>{s})); // __list_s__
var __functions_19__ = new Func<List<object>,string,object>((list,s) => {list.Add(s);return list;}); // __list_s__
var __actions_table__ = new IEnumerable<ParseAction<SymbolEnum,object>>[47,25];__actions_table__[0,8] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(true)};__actions_table__[2,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__optList_s__,
0,
null,
-1,
"Action for \"__optList_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<object>(() => __functions_9__()),0))
))};__actions_table__[3,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.typename,
1,
null,
-1,
"Action for \"typename\" at (59,21)",
null,
ProductionAction<object>.Convert(new Func<string,object>((id) => __functions_5__(id,null,null,null,null)),0))
))};__actions_table__[4,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.dot_identifier,
1,
null,
-1,
"Action for \"dot_identifier\" at (53,26)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object>((__merged_dot_identifier_id__) => __functions_3__(__merged_dot_identifier_id__)),0))
))};__actions_table__[5,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_dot_identifier_id____,
1,
null,
-1,
"Action for \"__list___merged_dot_identifier_id____\" at (53,26)",
null,
ProductionAction<object>.Convert(new Func<string,object>((id) => __functions_12__(id)),0))
))};__actions_table__[6,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.s,
3,
null,
-1,
"Action for \"s\" at (44,6)",
null,
ProductionAction<object>.Convert(new Func<object,string,object,object>((_0,t,_2) => __functions_0__(_0,t,_2)),1))
))};__actions_table__[7,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.whatever,
1,
null,
-1,
"Action for \"whatever\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object>((s) => __functions_6__(s)),0))
))};__actions_table__[8,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__optList_s__,
1,
null,
-1,
"Action for \"__optList_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object>((obj) => __functions_6__(obj)),0))
))};__actions_table__[9,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list_s__,
1,
null,
-1,
"Action for \"__list_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<object,object>((s) => __functions_16__(s)),0))
))};__actions_table__[10,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list_s__,
1,
null,
-1,
"Action for \"__list_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<string,object>((s) => __functions_18__(s)),0))
))};__actions_table__[19,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.typename,
2,
null,
-1,
"Action for \"typename\" at (59,21)",
null,
ProductionAction<object>.Convert(new Func<string,string,object>((id,a) => __functions_5__(id,null,null,null,a)),0))
))};__actions_table__[20,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.jagged_array,
1,
null,
-1,
"Action for \"jagged_array\" at (50,24)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object>((__merged_jagged_array_a__) => __functions_2__(__merged_jagged_array_a__)),0))
))};__actions_table__[21,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_jagged_array_a____,
1,
null,
-1,
"Action for \"__list___merged_jagged_array_a____\" at (50,24)",
null,
ProductionAction<object>.Convert(new Func<string,object>((a) => __functions_10__(a)),0))
))};__actions_table__[22,5] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__optList___merged_array_c____,
0,
null,
-1,
"Action for \"__optList___merged_array_c____\" at (47,26)",
null,
ProductionAction<object>.Convert(new Func<object>(() => __functions_9__()),0))
))};__actions_table__[24,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list_s__,
2,
null,
-1,
"Action for \"__list_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object,object>((list,s) => __functions_17__(list,s)),0))
))};__actions_table__[25,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list_s__,
2,
null,
-1,
"Action for \"__list_s__\" at (62,13)",
null,
ProductionAction<object>.Convert(new Func<List<object>,string,object>((list,s) => __functions_19__(list,s)),0))
))};__actions_table__[34,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.typename_list,
1,
null,
-1,
"Action for \"typename_list\" at (56,27)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object>((__merged_typename_list_t__) => __functions_4__(__merged_typename_list_t__)),0))
))};__actions_table__[35,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_typename_list_t____,
1,
null,
-1,
"Action for \"__list___merged_typename_list_t____\" at (56,27)",
null,
ProductionAction<object>.Convert(new Func<string,object>((t) => __functions_14__(t)),0))
))};__actions_table__[36,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_jagged_array_a____,
2,
null,
-1,
"Action for \"__list___merged_jagged_array_a____\" at (50,24)",
null,
ProductionAction<object>.Convert(new Func<List<string>,string,object>((list,a) => __functions_11__(list,a)),0))
))};__actions_table__[38,5] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__optList___merged_array_c____,
1,
null,
-1,
"Action for \"__optList___merged_array_c____\" at (47,26)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object>((obj) => __functions_6__(obj)),0))
))};__actions_table__[39,5] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_array_c____,
1,
null,
-1,
"Action for \"__list___merged_array_c____\" at (47,26)",
null,
ProductionAction<object>.Convert(new Func<object,object>((c) => __functions_7__(c)),0))
))};__actions_table__[40,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_dot_identifier_id____,
3,
null,
-1,
"Action for \"__list___merged_dot_identifier_id____\" at (53,26)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object,string,object>((list,_1,id) => __functions_13__(list,_1,id)),0))
))};__actions_table__[41,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.typename,
4,
null,
-1,
"Action for \"typename\" at (59,21)",
null,
ProductionAction<object>.Convert(new Func<string,object,string,object,object>((id,l,tt,r) => __functions_5__(id,l,tt,r,null)),0))
))};__actions_table__[43,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.array,
3,
null,
-1,
"Action for \"array\" at (47,17)",
null,
ProductionAction<object>.Convert(new Func<object,List<object>,object,object>((_0,__merged_array_c__,_2) => __functions_1__(_0,__merged_array_c__,_2)),1))
))};__actions_table__[44,5] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_array_c____,
2,
null,
-1,
"Action for \"__list___merged_array_c____\" at (47,26)",
null,
ProductionAction<object>.Convert(new Func<List<object>,object,object>((list,c) => __functions_8__(list,c)),0))
))};__actions_table__[45,1] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.typename,
5,
null,
-1,
"Action for \"typename\" at (59,21)",
null,
ProductionAction<object>.Convert(new Func<string,object,string,object,string,object>((id,l,tt,r,a) => __functions_5__(id,l,tt,r,a)),0))
))};__actions_table__[46,3] = new ParseAction<SymbolEnum,object>[]{new ParseAction<SymbolEnum,object>(false,ReductionAction.Create(NfaCell<SymbolEnum,object>.Create(
SymbolEnum.__list___merged_typename_list_t____,
3,
null,
-1,
"Action for \"__list___merged_typename_list_t____\" at (56,27)",
null,
ProductionAction<object>.Convert(new Func<List<string>,object,string,object>((list,_1,t) => __functions_15__(list,_1,t)),0))
))};
actionsTableDuplicates0(__actions_table__);
var __edges_table__ = ActionTableData<SymbolEnum,object>.CreateEdgesTable(47,25);
createEdges0(__edges_table__);
var __recovery_table__ = createRecoveryTable();
var symbols_rep = createSymbolsRep();
parser = new Parser<SymbolEnum,object>(new ActionTableData<SymbolEnum,object>(
actionsTable:__actions_table__,edgesTable:__edges_table__,recoveryTable:__recovery_table__,startSymbol:SymbolEnum.s,eofSymbol:SymbolEnum.EOF,syntaxErrorSymbol:SymbolEnum.Error,lookaheadWidth:1),symbols_rep);
return parser;
}

public static void actionsTableDuplicates0(IEnumerable<ParseAction<SymbolEnum,object>>[,] __actions_table__)
{
__actions_table__[1,9] = __actions_table__[0,8];
__actions_table__[2,2] = __actions_table__[0,8];
__actions_table__[2,3] = __actions_table__[0,8];
__actions_table__[2,4] = __actions_table__[0,8];
__actions_table__[2,5] = __actions_table__[0,8];
__actions_table__[2,6] = __actions_table__[0,8];
__actions_table__[2,7] = __actions_table__[0,8];
__actions_table__[2,8] = __actions_table__[0,8];
__actions_table__[2,9] = __actions_table__[0,8];
__actions_table__[2,10] = __actions_table__[0,8];
__actions_table__[3,2] = __actions_table__[0,8];
__actions_table__[3,3] = __actions_table__[3,1];
__actions_table__[3,4] = __actions_table__[0,8];
__actions_table__[3,5] = __actions_table__[3,1];
__actions_table__[3,6] = __actions_table__[3,1];
__actions_table__[3,7] = __actions_table__[3,1];
__actions_table__[3,8] = __actions_table__[3,1];
__actions_table__[3,9] = __actions_table__[3,1];
__actions_table__[3,10] = __actions_table__[3,1];
__actions_table__[4,2] = __actions_table__[4,1];
__actions_table__[4,3] = __actions_table__[4,1];
__actions_table__[4,4] = __actions_table__[4,1];
__actions_table__[4,5] = __actions_table__[4,1];
__actions_table__[4,6] = __actions_table__[0,8];
__actions_table__[4,7] = __actions_table__[4,1];
__actions_table__[4,8] = __actions_table__[4,1];
__actions_table__[4,9] = __actions_table__[4,1];
__actions_table__[4,10] = __actions_table__[4,1];
__actions_table__[5,2] = __actions_table__[5,1];
__actions_table__[5,3] = __actions_table__[5,1];
__actions_table__[5,4] = __actions_table__[5,1];
__actions_table__[5,5] = __actions_table__[5,1];
__actions_table__[5,6] = __actions_table__[5,1];
__actions_table__[5,7] = __actions_table__[5,1];
__actions_table__[5,8] = __actions_table__[5,1];
__actions_table__[5,9] = __actions_table__[5,1];
__actions_table__[5,10] = __actions_table__[5,1];
__actions_table__[8,2] = __actions_table__[0,8];
__actions_table__[8,3] = __actions_table__[0,8];
__actions_table__[8,4] = __actions_table__[0,8];
__actions_table__[8,5] = __actions_table__[0,8];
__actions_table__[8,6] = __actions_table__[0,8];
__actions_table__[8,7] = __actions_table__[0,8];
__actions_table__[8,8] = __actions_table__[0,8];
__actions_table__[8,9] = __actions_table__[0,8];
__actions_table__[8,10] = __actions_table__[0,8];
__actions_table__[9,2] = __actions_table__[9,1];
__actions_table__[9,3] = __actions_table__[9,1];
__actions_table__[9,4] = __actions_table__[9,1];
__actions_table__[9,5] = __actions_table__[9,1];
__actions_table__[9,6] = __actions_table__[9,1];
__actions_table__[9,7] = __actions_table__[9,1];
__actions_table__[9,8] = __actions_table__[9,1];
__actions_table__[9,9] = __actions_table__[9,1];
__actions_table__[9,10] = __actions_table__[9,1];
__actions_table__[10,2] = __actions_table__[10,1];
__actions_table__[10,3] = __actions_table__[10,1];
__actions_table__[10,4] = __actions_table__[10,1];
__actions_table__[10,5] = __actions_table__[10,1];
__actions_table__[10,6] = __actions_table__[10,1];
__actions_table__[10,7] = __actions_table__[10,1];
__actions_table__[10,8] = __actions_table__[10,1];
__actions_table__[10,9] = __actions_table__[10,1];
__actions_table__[10,10] = __actions_table__[10,1];
__actions_table__[11,1] = __actions_table__[9,1];
__actions_table__[11,2] = __actions_table__[9,1];
__actions_table__[11,3] = __actions_table__[9,1];
__actions_table__[11,4] = __actions_table__[9,1];
__actions_table__[11,5] = __actions_table__[9,1];
__actions_table__[11,6] = __actions_table__[9,1];
__actions_table__[11,7] = __actions_table__[9,1];
__actions_table__[11,8] = __actions_table__[9,1];
__actions_table__[11,9] = __actions_table__[9,1];
__actions_table__[11,10] = __actions_table__[9,1];
__actions_table__[12,1] = __actions_table__[9,1];
__actions_table__[12,2] = __actions_table__[9,1];
__actions_table__[12,3] = __actions_table__[9,1];
__actions_table__[12,4] = __actions_table__[9,1];
__actions_table__[12,5] = __actions_table__[9,1];
__actions_table__[12,6] = __actions_table__[9,1];
__actions_table__[12,7] = __actions_table__[9,1];
__actions_table__[12,8] = __actions_table__[9,1];
__actions_table__[12,9] = __actions_table__[9,1];
__actions_table__[12,10] = __actions_table__[9,1];
__actions_table__[13,1] = __actions_table__[9,1];
__actions_table__[13,2] = __actions_table__[9,1];
__actions_table__[13,3] = __actions_table__[9,1];
__actions_table__[13,4] = __actions_table__[9,1];
__actions_table__[13,5] = __actions_table__[9,1];
__actions_table__[13,6] = __actions_table__[9,1];
__actions_table__[13,7] = __actions_table__[9,1];
__actions_table__[13,8] = __actions_table__[9,1];
__actions_table__[13,9] = __actions_table__[9,1];
__actions_table__[13,10] = __actions_table__[9,1];
__actions_table__[14,1] = __actions_table__[9,1];
__actions_table__[14,2] = __actions_table__[9,1];
__actions_table__[14,3] = __actions_table__[9,1];
__actions_table__[14,4] = __actions_table__[9,1];
__actions_table__[14,5] = __actions_table__[9,1];
__actions_table__[14,6] = __actions_table__[9,1];
__actions_table__[14,7] = __actions_table__[9,1];
__actions_table__[14,8] = __actions_table__[9,1];
__actions_table__[14,9] = __actions_table__[9,1];
__actions_table__[14,10] = __actions_table__[9,1];
__actions_table__[15,1] = __actions_table__[9,1];
__actions_table__[15,2] = __actions_table__[9,1];
__actions_table__[15,3] = __actions_table__[9,1];
__actions_table__[15,4] = __actions_table__[9,1];
__actions_table__[15,5] = __actions_table__[9,1];
__actions_table__[15,6] = __actions_table__[9,1];
__actions_table__[15,7] = __actions_table__[9,1];
__actions_table__[15,8] = __actions_table__[9,1];
__actions_table__[15,9] = __actions_table__[9,1];
__actions_table__[15,10] = __actions_table__[9,1];
__actions_table__[16,1] = __actions_table__[9,1];
__actions_table__[16,2] = __actions_table__[9,1];
__actions_table__[16,3] = __actions_table__[9,1];
__actions_table__[16,4] = __actions_table__[9,1];
__actions_table__[16,5] = __actions_table__[9,1];
__actions_table__[16,6] = __actions_table__[9,1];
__actions_table__[16,7] = __actions_table__[9,1];
__actions_table__[16,8] = __actions_table__[9,1];
__actions_table__[16,9] = __actions_table__[9,1];
__actions_table__[16,10] = __actions_table__[9,1];
__actions_table__[17,1] = __actions_table__[9,1];
__actions_table__[17,2] = __actions_table__[9,1];
__actions_table__[17,3] = __actions_table__[9,1];
__actions_table__[17,4] = __actions_table__[9,1];
__actions_table__[17,5] = __actions_table__[9,1];
__actions_table__[17,6] = __actions_table__[9,1];
__actions_table__[17,7] = __actions_table__[9,1];
__actions_table__[17,8] = __actions_table__[9,1];
__actions_table__[17,9] = __actions_table__[9,1];
__actions_table__[17,10] = __actions_table__[9,1];
__actions_table__[18,9] = __actions_table__[0,8];
__actions_table__[19,2] = __actions_table__[19,1];
__actions_table__[19,3] = __actions_table__[19,1];
__actions_table__[19,4] = __actions_table__[19,1];
__actions_table__[19,5] = __actions_table__[19,1];
__actions_table__[19,6] = __actions_table__[19,1];
__actions_table__[19,7] = __actions_table__[19,1];
__actions_table__[19,8] = __actions_table__[19,1];
__actions_table__[19,9] = __actions_table__[19,1];
__actions_table__[19,10] = __actions_table__[19,1];
__actions_table__[20,2] = __actions_table__[20,1];
__actions_table__[20,3] = __actions_table__[20,1];
__actions_table__[20,4] = __actions_table__[0,8];
__actions_table__[20,5] = __actions_table__[20,1];
__actions_table__[20,6] = __actions_table__[20,1];
__actions_table__[20,7] = __actions_table__[20,1];
__actions_table__[20,8] = __actions_table__[20,1];
__actions_table__[20,9] = __actions_table__[20,1];
__actions_table__[20,10] = __actions_table__[20,1];
__actions_table__[21,2] = __actions_table__[21,1];
__actions_table__[21,3] = __actions_table__[21,1];
__actions_table__[21,4] = __actions_table__[21,1];
__actions_table__[21,5] = __actions_table__[21,1];
__actions_table__[21,6] = __actions_table__[21,1];
__actions_table__[21,7] = __actions_table__[21,1];
__actions_table__[21,8] = __actions_table__[21,1];
__actions_table__[21,9] = __actions_table__[21,1];
__actions_table__[21,10] = __actions_table__[21,1];
__actions_table__[22,7] = __actions_table__[0,8];
__actions_table__[23,9] = __actions_table__[0,8];
__actions_table__[24,2] = __actions_table__[24,1];
__actions_table__[24,3] = __actions_table__[24,1];
__actions_table__[24,4] = __actions_table__[24,1];
__actions_table__[24,5] = __actions_table__[24,1];
__actions_table__[24,6] = __actions_table__[24,1];
__actions_table__[24,7] = __actions_table__[24,1];
__actions_table__[24,8] = __actions_table__[24,1];
__actions_table__[24,9] = __actions_table__[24,1];
__actions_table__[24,10] = __actions_table__[24,1];
__actions_table__[25,2] = __actions_table__[25,1];
__actions_table__[25,3] = __actions_table__[25,1];
__actions_table__[25,4] = __actions_table__[25,1];
__actions_table__[25,5] = __actions_table__[25,1];
__actions_table__[25,6] = __actions_table__[25,1];
__actions_table__[25,7] = __actions_table__[25,1];
__actions_table__[25,8] = __actions_table__[25,1];
__actions_table__[25,9] = __actions_table__[25,1];
__actions_table__[25,10] = __actions_table__[25,1];
__actions_table__[26,1] = __actions_table__[24,1];
__actions_table__[26,2] = __actions_table__[24,1];
__actions_table__[26,3] = __actions_table__[24,1];
__actions_table__[26,4] = __actions_table__[24,1];
__actions_table__[26,5] = __actions_table__[24,1];
__actions_table__[26,6] = __actions_table__[24,1];
__actions_table__[26,7] = __actions_table__[24,1];
__actions_table__[26,8] = __actions_table__[24,1];
__actions_table__[26,9] = __actions_table__[24,1];
__actions_table__[26,10] = __actions_table__[24,1];
__actions_table__[27,1] = __actions_table__[24,1];
__actions_table__[27,2] = __actions_table__[24,1];
__actions_table__[27,3] = __actions_table__[24,1];
__actions_table__[27,4] = __actions_table__[24,1];
__actions_table__[27,5] = __actions_table__[24,1];
__actions_table__[27,6] = __actions_table__[24,1];
__actions_table__[27,7] = __actions_table__[24,1];
__actions_table__[27,8] = __actions_table__[24,1];
__actions_table__[27,9] = __actions_table__[24,1];
__actions_table__[27,10] = __actions_table__[24,1];
__actions_table__[28,1] = __actions_table__[24,1];
__actions_table__[28,2] = __actions_table__[24,1];
__actions_table__[28,3] = __actions_table__[24,1];
__actions_table__[28,4] = __actions_table__[24,1];
__actions_table__[28,5] = __actions_table__[24,1];
__actions_table__[28,6] = __actions_table__[24,1];
__actions_table__[28,7] = __actions_table__[24,1];
__actions_table__[28,8] = __actions_table__[24,1];
__actions_table__[28,9] = __actions_table__[24,1];
__actions_table__[28,10] = __actions_table__[24,1];
__actions_table__[29,1] = __actions_table__[24,1];
__actions_table__[29,2] = __actions_table__[24,1];
__actions_table__[29,3] = __actions_table__[24,1];
__actions_table__[29,4] = __actions_table__[24,1];
__actions_table__[29,5] = __actions_table__[24,1];
__actions_table__[29,6] = __actions_table__[24,1];
__actions_table__[29,7] = __actions_table__[24,1];
__actions_table__[29,8] = __actions_table__[24,1];
__actions_table__[29,9] = __actions_table__[24,1];
__actions_table__[29,10] = __actions_table__[24,1];
__actions_table__[30,1] = __actions_table__[24,1];
__actions_table__[30,2] = __actions_table__[24,1];
__actions_table__[30,3] = __actions_table__[24,1];
__actions_table__[30,4] = __actions_table__[24,1];
__actions_table__[30,5] = __actions_table__[24,1];
__actions_table__[30,6] = __actions_table__[24,1];
__actions_table__[30,7] = __actions_table__[24,1];
__actions_table__[30,8] = __actions_table__[24,1];
__actions_table__[30,9] = __actions_table__[24,1];
__actions_table__[30,10] = __actions_table__[24,1];
__actions_table__[31,1] = __actions_table__[24,1];
__actions_table__[31,2] = __actions_table__[24,1];
__actions_table__[31,3] = __actions_table__[24,1];
__actions_table__[31,4] = __actions_table__[24,1];
__actions_table__[31,5] = __actions_table__[24,1];
__actions_table__[31,6] = __actions_table__[24,1];
__actions_table__[31,7] = __actions_table__[24,1];
__actions_table__[31,8] = __actions_table__[24,1];
__actions_table__[31,9] = __actions_table__[24,1];
__actions_table__[31,10] = __actions_table__[24,1];
__actions_table__[32,1] = __actions_table__[24,1];
__actions_table__[32,2] = __actions_table__[24,1];
__actions_table__[32,3] = __actions_table__[24,1];
__actions_table__[32,4] = __actions_table__[24,1];
__actions_table__[32,5] = __actions_table__[24,1];
__actions_table__[32,6] = __actions_table__[24,1];
__actions_table__[32,7] = __actions_table__[24,1];
__actions_table__[32,8] = __actions_table__[24,1];
__actions_table__[32,9] = __actions_table__[24,1];
__actions_table__[32,10] = __actions_table__[24,1];
__actions_table__[33,3] = __actions_table__[0,8];
__actions_table__[34,7] = __actions_table__[0,8];
__actions_table__[35,7] = __actions_table__[35,3];
__actions_table__[36,2] = __actions_table__[36,1];
__actions_table__[36,3] = __actions_table__[36,1];
__actions_table__[36,4] = __actions_table__[36,1];
__actions_table__[36,5] = __actions_table__[36,1];
__actions_table__[36,6] = __actions_table__[36,1];
__actions_table__[36,7] = __actions_table__[36,1];
__actions_table__[36,8] = __actions_table__[36,1];
__actions_table__[36,9] = __actions_table__[36,1];
__actions_table__[36,10] = __actions_table__[36,1];
__actions_table__[37,5] = __actions_table__[0,8];
__actions_table__[38,7] = __actions_table__[0,8];
__actions_table__[39,7] = __actions_table__[39,5];
__actions_table__[40,2] = __actions_table__[40,1];
__actions_table__[40,3] = __actions_table__[40,1];
__actions_table__[40,4] = __actions_table__[40,1];
__actions_table__[40,5] = __actions_table__[40,1];
__actions_table__[40,6] = __actions_table__[40,1];
__actions_table__[40,7] = __actions_table__[40,1];
__actions_table__[40,8] = __actions_table__[40,1];
__actions_table__[40,9] = __actions_table__[40,1];
__actions_table__[40,10] = __actions_table__[40,1];
__actions_table__[41,2] = __actions_table__[41,1];
__actions_table__[41,3] = __actions_table__[41,1];
__actions_table__[41,4] = __actions_table__[0,8];
__actions_table__[41,5] = __actions_table__[41,1];
__actions_table__[41,6] = __actions_table__[41,1];
__actions_table__[41,7] = __actions_table__[41,1];
__actions_table__[41,8] = __actions_table__[41,1];
__actions_table__[41,9] = __actions_table__[41,1];
__actions_table__[41,10] = __actions_table__[41,1];
__actions_table__[42,9] = __actions_table__[0,8];
__actions_table__[43,2] = __actions_table__[43,1];
__actions_table__[43,3] = __actions_table__[43,1];
__actions_table__[43,4] = __actions_table__[43,1];
__actions_table__[43,5] = __actions_table__[43,1];
__actions_table__[43,6] = __actions_table__[43,1];
__actions_table__[43,7] = __actions_table__[43,1];
__actions_table__[43,8] = __actions_table__[43,1];
__actions_table__[43,9] = __actions_table__[43,1];
__actions_table__[43,10] = __actions_table__[43,1];
__actions_table__[44,7] = __actions_table__[44,5];
__actions_table__[45,2] = __actions_table__[45,1];
__actions_table__[45,3] = __actions_table__[45,1];
__actions_table__[45,4] = __actions_table__[45,1];
__actions_table__[45,5] = __actions_table__[45,1];
__actions_table__[45,6] = __actions_table__[45,1];
__actions_table__[45,7] = __actions_table__[45,1];
__actions_table__[45,8] = __actions_table__[45,1];
__actions_table__[45,9] = __actions_table__[45,1];
__actions_table__[45,10] = __actions_table__[45,1];
__actions_table__[46,7] = __actions_table__[46,3];
}
}
}
