/* --------------------------------------------------------------------------
THIS FILE WAS AUTOMATICALLY GENERATED BY NLT SUITE FROM "NaiveLanguageTools.Generator/AST/CodeParser/Syntax.nlg" FILE
-------------------------------------------------------------------------- */

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using NaiveLanguageTools.Common;
using NaiveLanguageTools.Parser;
using NaiveLanguageTools.Parser.Automaton;
using NaiveLanguageTools.Parser.Symbols;
using NaiveLanguageTools.Lexer;
using NaiveLanguageTools.MultiRegex.Dfa;

namespace NaiveLanguageTools.Generator.AST.CodeParser
{
public enum SymbolEnum
{
Error,
EOF,
LANGLE,
RANGLE,
LBRACKET,
RBRACKET,
DOT,
COMMA,
NEW,
IDENTIFIER,
WHATEVER,
s,
array,
jagged_array,
dot_identifier,
typename_list,
typename,
whatever,
__list___merged_array_c____,
__optList___merged_array_c____,
__list___merged_jagged_array_a____,
__list___merged_dot_identifier_id____,
__list___merged_typename_list_t____,
__list_s__,
__optList_s__
}
}
